/* eslint-disable @typescript-eslint/ban-ts-comment */
import { getQueryClientForHydration } from "@/libs/react-query";
import "@/styles/index.css";
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from "next/script";
import { PropsWithChildren } from "react";
import { currentUserQuery } from "./hooks/current-user";
import { ClientProviders } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Client care",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: PropsWithChildren) => {
  const queryClient = getQueryClientForHydration();
  const currentUserResponse = await queryClient.fetchQuery(currentUserQuery);
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProviders>
          <HydrationBoundary
            state={
              "message" in currentUserResponse ? undefined : dehydratedState
            }
          >
            {children}
          </HydrationBoundary>
        </ClientProviders>

        {/* @ts-ignore */}
        <feedback-widget
          dev={process.env.NODE_ENV !== "production" ? "true" : undefined}
          token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0SWQiOiJjbTJhbXJzdXgwMDAwaHdlN2sya2ppOWd6Iiwib3JnYW5pemF0aW9uSWQiOiJjbTI4MDd5ZHAwMDAzZzZzNGZydGR1czNmIiwid2lkZ2V0SWQiOiJjbTJkaDAzZm0wMDAwMTE1YmhqdWd1OGFuIiwiaWF0IjoxNzI5MzI3OTQ1LCJleHAiOjMzMjU1MzcwMzQ1fQ.4D9fyEXxBO5ZOsrDQWULszZ9RRU70sN9cPN7K5KWPQA"
        >
          {/* @ts-ignore */}
        </feedback-widget>
        <Script src="https://client-care-widget-dev.vercel.app/widget.umd.js" />
      </body>
    </html>
  );
};

export default RootLayout;
